import { ESCOLAS_ENDPOINT } from ".";
import type { Estado } from "./estados";

// Generated by https://quicktype.io

export type Escola = {
    anoCenso: number;
    cod: number;
    nome: string;
    codCidade: number;
    cidade: string;
    estado: string;
    regiao: Regiao;
    // situacaoFuncionamento: number;
    // dependenciaAdministrativa: number;
    // idebAI: number;
    // idebAF: number;
    enemMediaGeral: number;
    situacaoFuncionamentoTxt: SituacaoFuncionamentoTxt;
    dependenciaAdministrativaTxt: DependenciaAdministrativaTxt;
    [key: string]: any;
}

export enum DependenciaAdministrativaTxt {
    Estadual = "Estadual",
    Municipal = "Municipal",
    Privada = "Privada",
}

export enum Regiao {
    Nordeste = "Nordeste",
    Norte = "Norte",
    Sudeste = "Sudeste",
    Sul = "Sul",
}

export enum SituacaoFuncionamentoTxt {
    EmAtividade = "Em atividade",
    Paralisada = "Paralisada",
}

export type Cidade = {
    id: number,
    nome: string
};

export async function getCidadesDeEstado(estado: Estado): Promise<Array<Cidade>> {
    const response = await fetch(ESCOLAS_ENDPOINT + `cidades/${estado.sigla.toLowerCase()}`);
    const data: string[] = await response.json();

    return data.map(line => {
        const [id, nome] = line.split(":");

        return {
            id: +id,
            nome
        } as Cidade;
    })
}

export async function searchForSchool(name: string, estado: Estado): Promise<Array<Escola>> {
    const response = await fetch(ESCOLAS_ENDPOINT + `escolas/buscaavancada?nome=${name}&estado=${estado.sigla}`);
    const data: Array<Escola> = await response.json()[1];

    return data;
}