// Generated by https://quicktype.io
import { IBGE_ENDPOINT, BANDEIRAS_ENDPOINT } from "./index"

export interface Region {
    id: number;
    sigla: string;
    nome: string;
}

export interface Estado {
    id: number;
    sigla: string;
    nome: string;
    regiao?: Region;
}

export async function getEstados(): Promise<Array<Estado>> {
    const response = await fetch(IBGE_ENDPOINT);
    const data = await response.json();
    return data;
}

export function getImagemBandeiraURL(sigla: string): string {
    return BANDEIRAS_ENDPOINT + sigla.toUpperCase() + ".png";
}